// Offline geometry review of the compiled database.
const fs=require('node:fs'),path=require('node:path');
const {readLua}=require('./lua-data');
const {unpackRuns}=require('./packed-runs');
const root=path.resolve(__dirname,'..'),env={};
for(const name of ['Init','Quests','Locations']) readLua(path.join(root,'Data',name+'.lua'),env);
const db=env.QuestlineDB,ids=[844,845,903,855,895,881,900,869];
for(const target of Object.values(db.locations)) for(const data of Object.values(target)) data.runs=unpackRuns(data.runs);
const examples=ids.map(id=>{const q=db.quests[id],complete=id===869;return {id,title:q.title,summary:q.summary,complete,targets:Object.values(complete?q.finishers:q.objectives).map(t=>({...t,location:db.locations[t.key]?.[17]}))};});
const json=JSON.stringify(examples).replace(/</g,'\\u003c');
const html=String.raw`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Questline · Barrens geometry preview</title>
<style>*{box-sizing:border-box}body{margin:0;background:#0b121a;color:#e7e7de;font:15px system-ui,sans-serif}header{padding:24px 32px;border-bottom:1px solid #35424c}h1{font-size:26px;margin:0 0 6px;color:#ffd372}p{margin:7px 0;color:#a7b6c5}main{display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:20px;padding:24px}svg{background:#172431;border:1px solid #384b5a;border-radius:8px;width:100%}aside{display:flex;flex-direction:column;gap:6px}button{cursor:pointer;display:flex;align-items:center;gap:10px;text-align:left;border:1px solid #34434f;border-radius:7px;color:#e9cd86;background:#15212b;padding:12px;font:inherit}button.active{background:#20475b;border-color:#79cbff;color:#fff}b{display:grid;place-items:center;border-radius:100%;width:26px;height:26px;border:1px solid #c39b4f;flex-shrink:0}#detail{padding:16px 4px}footer{padding:0 26px 24px;color:#95aabb}@media(max-width:800px){main{grid-template-columns:1fr}aside{max-width:100%}}</style>
<header><h1>Questline <span style="color:#8ed5ff">/ The Barrens</span></h1><p>Compiled area preview. Coordinate grid only; terrain and the actual tracker are shown in game.</p></header>
<main><section><svg id="map" viewBox="0 0 1000 668" role="img" aria-label="Barrens quest area coordinates"></svg><div id="detail"></div></section><aside id="quests"></aside></main><footer>Open the Barrens map in WoW to inspect quests from your quest log. Blue areas approximate spawn coverage; small locations use action icons. This page reads Questline's generated database, without pfQuest.</footer>
<script>const quests=${json},grid=${db.grid};let active=0;const arr=o=>Object.values(o||{});const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function choose(index){active=index;render()}function render(){let svg='';for(let n=0;n<=100;n+=10)svg+='<path d="M '+n*10+' 0 V 668 M 0 '+n*6.68+' H 1000" stroke="#2c3d4c" stroke-width="1"/><text x="'+(n*10+3)+'" y="15" fill="#718ca0" font-size="12">'+n+'</text>';const q=quests[active];let spawns=0,points=0;for(const t of q.targets){const d=t.location;if(!d)continue;spawns+=d.spawns;const runs=arr(d.runs);for(let i=0;i<runs.length;i+=3)svg+='<rect x="'+runs[i+1]/grid*1000+'" y="'+runs[i]/grid*668+'" width="'+(runs[i+2]-runs[i+1])/grid*1000+'" height="'+668/grid+'" fill="#408eff" fill-opacity=".36"/>';for(const p of arr(d.points)){points++;svg+='<g><circle cx="'+p[1]*10+'" cy="'+p[2]*6.68+'" r="9" fill="#1c252c" stroke="#ffd372"/><title>'+esc(t.name)+'</title></g>';}}for(const [x,y,label] of [[52.2,31,'Crossroads'],[62.7,36.2,'Ratchet'],[45.3,59,'Camp Taurajo']])svg+='<text x="'+(x*10+5)+'" y="'+(y*6.68+20)+'" fill="#a6b9c8" font-size="13">'+label+'</text>';quests.forEach((entry,i)=>{const target=entry.targets.find(t=>t.location);if(!target)return;const a=target.location.anchor;svg+='<g tabindex="0" role="button" aria-label="'+esc(entry.title)+'" style="cursor:pointer" onclick="choose('+i+')" onkeydown="if(event.key===\'Enter\'||event.key===\' \'){event.preventDefault();choose('+i+')}" transform="translate('+a[1]*10+' '+a[2]*6.68+')"><circle r="13" fill="'+(i===active?'#24577b':'#1a2025')+'" stroke="'+(i===active?'#8cd7ff':'#d2aa57')+'" stroke-width="2"/><text text-anchor="middle" y="5" fill="#ffe7a2" font-size="14">'+(entry.complete?'?':i+1)+'</text><title>'+esc(entry.title)+'</title></g>';});document.querySelector('#map').innerHTML=svg;document.querySelector('#quests').innerHTML=quests.map((entry,i)=>'<button class="'+(i===active?'active':'')+'" onclick="choose('+i+')"><b>'+(entry.complete?'?':i+1)+'</b>'+esc(entry.title)+'</button>').join('');document.querySelector('#detail').innerHTML='<strong>'+esc(q.title)+'</strong><p>'+esc(q.summary)+'</p><p>'+spawns+' source coordinates · '+points+' precise markers · '+(q.complete?'Ready for turn-in':'Only this quest is shaded')+'</p>';}render();</script></html>`;
fs.writeFileSync(path.join(root,'reports','Barrens-preview.html'),html);
console.log('Wrote reports/Barrens-preview.html');
